---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: "Check if docker is installed"
    package_facts:
      manager: "auto"

  - name: "Package check result"
    ansible.builtin.fail:
      msg: Docker package not found
    failed_when: true
    when: "'docker-ce' not in ansible_facts.packages"
